services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-electron-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true